services:
  - type: web
    name: gestion-finances-amani
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn church_finance.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-finances-db
          property: connectionString

