services:
  - type: web
    name: gestion-finances-eglise
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gestion_finances_eglise.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-finances-db
          property: connectionString

